# -*- coding: utf-8 -*-
"""205090407111014_Dian Alhusari_Tugas1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_MfK4icuM1UhhVLi5G_hwdmr-G73Hv1c
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
conf19 = pd.read_csv('time_series_covid19_confirmed_global.csv')
print(conf19)

#membuat data asia tenggara
asia =  ['Kamboja','Laos','Myanmar','Thailand','Vietnam','Brunei','Filipina','Indonesia','Malaysia','Singapura','Timor-Leste']
df_asia = conf19.loc[
                conf19['Country/Region'].isin(asia)
                & conf19['Province/State'].isna()]
print(df_asia)

#menghapus kolom
df_asia = df_asia.drop(['Province/State','Lat','Long'],axis = 1) 
print(df_asia)

df_asia.rename(index=lambda x: df_asia.at[x,'Country/Region'], inplace=True) #mengubah index menjadi negara
print(df_asia)

#tranpose dataframe
trans_asia = df_asia.transpose()
print(trans_asia)

trans_asia = trans_asia.drop(['Country/Region']) #mengapus baris negara
trans_asia.index = pd.to_datetime(trans_asia.index) #mengubah index menjadi tanggal
print(trans_asia)

#membuat line plot data asia tenggara
trans_asia.plot(figsize=(15,10))
plt.title('perkembangan terkonfirmasi covid-19 di Asia Tenggara')
plt.xlabel('Dates')
plt.ylabel('confirmed covid ( juta )') 
plt.show()